spring.application.name=learning
#datasource configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/BookApp?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&reWriteBatchedInserts=true
spring.datasource.username=ioana
spring.datasource.password=parola
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.serialization.fail-on-empty-beans=false
#server.port=8090

#Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/book_rental
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/book_rental/protocol/openid-connect/certs

spring.security.oauth2.client.registration.my-login-client.client-id=book_rental
spring.security.oauth2.client.registration.my-login-client.client-secret=gvBOd3BrqOS8LGqhF7Fh26f2z28Nbs2J
spring.security.oauth2.client.registration.my-login-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.my-login-client.scope=openid,profile
spring.security.oauth2.client.registration.my-login-client.provider=book-rental-auth
spring.security.oauth2.client.provider.book-rental-auth.token-uri=http://localhost:9090/realms/book_rental/protocol/openid-connect/token
spring.security.oauth2.client.provider.book-rental-auth.issuer-uri=http://localhost:9090/realms/book_rental
spring.security.oauth2.client.provider.book-rental-auth.jwk-set-uri=http://localhost:9090/realms/book_rental/protocol/openid-connect/certs

auth.oauth2.server-url=http://localhost:9090
auth.oauth2.realm=book_rental
auth.oauth2.admin.username=admin
auth.oauth2.admin.password=admin
auth.oauth2.admin.client-id=admin-cli
auth.oauth2.admin.realm=master

# DDL generation
spring.jpa.generate-ddl=true
server.servlet.contextPath=/api
spring.jpa.show-sql=true

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jpa.properties.hibernate.format_sql=true

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ioanaardelean199@gmail.com
spring.mail.password=qsuxoserhhcuxplp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Batch
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
logging.level.org.hibernate.session.metrics=debug
